title: Lee Barnett
description: Artisanal leadership

url: http://www.leebarnett.net
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: redcarpet
highlighter: pygments
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Contact
   url: /contact

social:
   github: leebarnett
   twitter: leebarnettsays
   instagram: leebarnettsays
   email: lee.barnett@mac.com

google_analytics: 
